# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  weight = 10

[[main]]
  name = "About Us"
  parent = "About"
  pageRef = "about"
  weight = 11

[[main]]
  name = "History & Legacy"
  parent = "About"
  pageRef = "history"
  weight = 12

[[main]]
  name = "Contact Us"
  parent = "About"
  pageRef = "contact"
  weight = 13

[[main]]
  name = "Harewire"
  parent = "About"
  pageRef = "harewire"
  weight = 14

[[main]]
  name = "News"
  weight = 20

[[main]]
  name = "Gang News"
  parent = "News"
  pageRef = "news"
  weight = 21

[[main]]
  name = "Operations"
  parent = "News"
  pageRef = "ops"
  weight = 22

[[main]]
  name = "Members"
  weight = 30

[[main]]
  name = "Gang Members"
  parent = "Members"
  pageRef = "members"
  weight = 31

[[main]]
  name = "Leadership"
  parent = "Members"
  pageRef = "leadership"
  weight = 32

[[main]]
  name = "Roles"
  parent = "Members"
  pageRef = "roles"
  weight = 33

[[main]]
  name = "Roster"
  parent = "Members"
  pageRef = "roster"
  weight = 34

[[main]]
  pre = "facebook"
  title = "Facebook"
  url = "https://facebook.com/nousagigangph"
  weight = 50

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Gaming Guidelines"
  pageRef = "gaming-guidelines"
  weight = 10

[[footer]]
  name = "HOP Protocol"
  pageRef = "hop-protocol"
  weight = 11

[[footer]]
  name = "Privacy Policy"
  pageRef = "legal"
  weight = 12

[[footer]]
  name = "Site Resources"
  pageRef = "resources"
  weight = 13
